name: Testing Actions with AWS

on: [push]

jobs:
  List-all-S3-Buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Run AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: List Buckets
        run: |
          aws s3 ls
